name: SQL Server Automation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SQL Server
      run: |
        sudo apt-get install -y mssql-tools unixodbc-dev
        sqlcmd -S tcp:0.tcp.ngrok.io,14614 -U Auto_user -P 'YourPassword' -Q "CREATE DATABASE AutoTest"
        sqlcmd -S tcp:0.tcp.ngrok.io,14614 -U Auto_user -P 'YourPassword' -d AutoTest -i sql_setup.sql

    - name: Insert data
      run: |
        sqlcmd -S tcp:0.tcp.ngrok.io,14614 -U Auto_user -P 'YourPassword' -d AutoTest -Q "EXEC InsertUser 'John', 'Doe', 'john.doe@example.com'"
