name: SQL Server Automation

on:
  push:
    branches:
      - main

jobs:
  automate-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run SQL Scripts
        env:
          SQL_SERVER: 'tcp://0.tcp.ngrok.io:14614' # Replace with your ngrok URL
          SQL_USER: 'Auto_user'
          SQL_PASSWORD: 'YourStrongPassword'
        run: |
          sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -i DatabaseAdministration/sql_setup.sql
          sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -Q "EXEC AutoTest.dbo.InsertUser @Name='John', @Surname='Doe', @Email='john.doe@example.com';"
